CREATE TYPE "NotificationType" AS ENUM (
  'TASK_ASSIGNED',
  'TASK_SUBMITTED',
  'TASK_REVIEWED',
  'TASK_NEEDS_REVISION',
  'TASK_COMPLETED',
  'EXTERNAL_FEEDBACK_ADDED',
  'TRAINING_STATUS_CHANGED'
);

ALTER TABLE "Notification"
ADD COLUMN "type" "NotificationType" NOT NULL DEFAULT 'TASK_ASSIGNED';
